<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post">
              <div class="form-group">
                <input type="text" name="nome" class="form-control" placeholder="Nome" value="<?= $this->view->usuario['nome'] ?? '' ?>">
              </div>
              
              <div class="form-group">
                <input type="text" name="email" class="form-control" placeholder="E-mail" value="<?= $this->view->usuario['email'] ?? '' ?>">
              </div>

              <div class="form-group">
                <input type="password" name="senha" class="form-control" placeholder="Senha" value="<?= $this->view->usuario['senha'] ?? '' ?>">                
                <?=  $this->view->errorCadastro ? '<small class="form-text text-center text-danger">Verifique os campos e preencha novamente.</small>' : '' ?>
              </div>
              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>
            </form>
              
          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  